blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^about.html$', views.about, name='about'),
    url(r'^archives.html$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
]

webproject/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.feeds import AllPostsRssFeed
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('blog.urls')),
    path(r'rss/', AllPostsRssFeed(), name='rss'),
    path(r'mdeditor/', include('mdeditor.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from mdeditor.fields import MDTextField
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=70)

    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)

    excerpt = models.CharField(max_length=200, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    content = MDTextField()
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

blog/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage, InvalidPage
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Article, Category, Tag
import markdown

# Create your views here.
def index(request):
    article_list = Article.objects.all().order_by('-created_time')
    paginator = Paginator(article_list, 10)
    page = request.GET.get('page')

    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    
    return render(request, 'blog/index.html', context={'article_list': articles})


def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    article_list = Article.objects.filter(category=cate).order_by('-created_time')
    
    return render(request, 'blog/index.html', context={'article_list': article_list})

def about(request):
   category_list = Category.objects.all()
   return render(request, 'blog/about.html', context={'category_list': category_list})

def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.content = markdown.markdown(article.content,
                                        extensions=[
                                            'markdown.extensions.extra',
                                            'markdown.extensions.codehilite',
                                            'markdown.extensions.toc',
                                        ])

    return render(request, 'blog/detail.html', context={'article': article})


def archives(request):
    dates = Article.objects.datetimes('created_time', 'month', order='DESC')
    article_list = Article.objects.all().order_by('-created_time')
 
    return render(request, 'blog/archives.html', context={'dates' : dates,
                                                        'article_list': article_list})

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="longfellow的个人网站">
  <meta name="author" content="longfellow">

  <title>longFellow</title>

  <link rel="shortcut icon" href="{%static 'images/favicon.ico' %}">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/index.css' %}" rel="stylesheet">
  <link href="{% static 'css/common.css' %}" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
  <!--link href="{% static 'vendor/bootstrap/highlights/github.css' %}" rel="stylesheet"-->
</head>

<body>

    <header class="site-header">
        <div class="site-header-topbar">
            <div class="container">
                <div class="topbar-menu">
                    <div class="item">
                        <a href="#" target="_self" title="笔记">
                            笔记
                        </a>
                    </div>
                    <div class="item">
                        <a href="/admin" target="_self" title="博客">
                            博客
                        </a>
                    </div>
                    <div class="item">
                        <a href="mailto:longfellow.wang@gmail.com" target="_self" title="Gmail"">
                            Gmail
                        </a>
                    </div>
                    <div class="item">
                        <a href="/about.html" target="_self" title="关于">
                            关于
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <a id="site-header-brand" href="/" title="longfellow">
                <span class="octicon octicon-smiley"></span>
                longfellow
            </a>
            <nav class="site-header-nav" role="navigation">
                <div class=" site-header-nav-item hvr-underline-from-center">
                    <a href="/" target="" title="Home">
                        Home
                    </a>
                </div>
                <!--div class=" site-header-nav-item hvr-underline-from-center">
                    <a href="/spring-cloud.html" target="_self" title="Spring Cloud">
                        Spring Cloud
                    </a>
                </div-->
                <div class=" site-header-nav-item hvr-underline-from-center">
                    <a href="/archives.html" target="_self" title="Archives">
                        Archives
                    </a>
                </div>
            </nav>
        </div>
    </header>

<div class="content">
    
    <section class="jumbotron">
        <div class="container">
            <h2>What the Heart of the Young Man</h2>
        </div>
    </section>

    <section class="content container">
        <div class="row">
            <!-- Post List -->
                {% block main %}
                
                <!-- Pagination -->
                {% block pagination %}
                {% endblock pagination %}
                
                {% endblock main %}


            {% block sidebar %}
            {% endblock sidebar %}

        </div>
    </section>
</div>

<!-- Footer -->
<footer class="container">
    <div class="site-footer">
        <div class="copyright pull-left">
            <a href="https://github.com/DONGChuan/Yummy-Jekyll">Yummy Jekyll</a>
        </div>

        <div class="pull-right">
            <a href="javascript:window.scrollTo(0,0)" >TOP</a>
        </div>
    </div>

    <div class="pull-mid">
        <p>Copyright &copy; longfellow.wang@gmail.com</p>
    </div>
    
    <!-- Third-Party JS -->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/geopattern.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</footer>

</html>

templates/blog/about.html
{% extends 'base.html' %}
{% block main %}
<!-- Blog Entries Column -->
    <h1>
        About | 个人简介
    </h1>
    <hr>
    <!-- Blog Post -->
    <div class="col-md-12">
    <!--img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap"-->
        <div class="card-body">
            <h2 class="card-title">教育经历</h2>
            <hr>
            <p class="card-text">2013.08-2017.06 东南大学                 计算机科学与技术</p>
        </div>
        <div class="card-body">
            <h2 class="card-title">工作经历</h2>
            <hr>
            <p class="card-text">2017.04-2017.12 上海聚力传媒技术有限公司 Python开发工程师</p>
            <p calss="card-text">2017.12-至今    广州优普计算机有限公司   大数据开发工程师</p>
        </div>
    </div>
{% endblock main %}

templates/blog/archives.html
{% extends 'base.html' %}
{% load blog_extras %}
{% block main %}

<section class="post container">
    <section class="label-section">
        <h3><small>标签列表</small></h3>
        <hr>
    
        {% get_tags as tag_list %}
        <div>
            {% for tag in tag_list %}
                <span class="post-label">{{ tag.name }}</span>
            {% empty %}
                <span class="post-label">暂无标签</span>
            {% endfor %}
        </div>
    
    </div>
    
    <ul class="archives-list">
    {% regroup article_list by created_time.year as year_article_list %}
        {% for year in year_article_list %}
        <h3>{{ year.grouper }} 年</h3>
            {% for article in year.list %}
            <li>
                <span><td>{{ article.created_time|date:"m-d" }}</td></span>
                <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
            </li>
            {% endfor %}
        {% endfor %}
    </ul>
</section>

{% endblock main %}

templates/blog/category.html
{% extends 'base.html' %}
{% block main %}
<!-- Blog Entries Column -->
    <h1 class="my-4">
        <small>Tags</small>
    </h1>

    <!-- Blog Post -->
    <div class="card mb-4">
    <!--img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap"-->
    
        <div class="card-body">
            {% for tag in tag_list %}
                <span class="post-label select">{{ tag.name }}</span>
            {% empty %}
                <span class="post-label select">暂时还没有发布的文章！</span>
            {% endfor %}
        </div>
    </div>
{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
<!-- Blog Post -->
    <div class="col-md-12 markdown-body">
        <h2 class="card-title">{{ article.title }}</h2>
            <div class="card-footer text-muted">
                Posted on {{ article.created_time }} by
                <a href="/about.html">{{ article.author }}</a>
            </div>
        <hr>
        <p class="card-text">{{ article.content|safe }}</p>
    </div>
{% endblock main %}

{% block pagination %}
<ul class="pagination justify-content-center mb-4">
    <li class="page-item">
        <a class="page-link" href="#">&larr; Older</a>
    </li>
    <li class="page-item disabled">
        <a class="page-link" href="#">Newer &rarr;</a>
    </li>
</ul>
{% endblock pagination %}

templates/blog/index.html
{% extends 'base.html' %}
{% load blog_extras %}
<!-- Blog Post -->
{% block main %}
<div class="col-md-8">
    <ol class="post-list">
        {% for article in article_list %}

        <li class="post-list-item">
            <h3 class="post-list-title">
                <a class="hvr-underline-from-center" href="{{ article.get_absolute_url }}">{{ article.title }}</a>
            </h3>

            <p class="post-list-description">{{ article.excerpt }}</p>
            <p class="post-list-meta">
                <span class="octicon octicon-calendar"></span> Posted on {{ article.created_time }} by
                <a href="/about.html">{{ article.author }}</a>
            </p>
        </li>

        {% empty %}
        <li class="post-list-item">
            <h3 class="post-list-title">
                暂时还没有发布的文章！
            </h3>
        </li>
        {% endfor %}
    </ol>

    {% block pagination %}
    <div class="pagination text-align">
        <div class="btn-group">
            {% if article_list.has_previous %}
                <button disabled="disabled" href="?page={{ article_list.previous_page_number }}" class="btn btn-outline">«</button>
            {% endif %}
            
            <button class="btn btn-outline">
                On <a>{{ article_list.number }}</a> - All <a>{{ article_list.paginator.num_pages }}</a>
            </button>
            <!--a href="javascript:;" class="active btn btn-outline">1</a-->
            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}" class="btn btn-outline">»</a>
            {% endif %}
        </div>
    </div>
    {% endblock pagination %}

</div>
{% endblock main %}



<!-- 侧边栏 -->
{% block sidebar %}
<div class="col-md-4">
    <!-- 外部链接Github，知乎，微博，RSS -->
    <div class="card text-center">
        <div class="thumbnail">
                <div class="card-description">
                    <ul class="list-inline" style="margin-left: 0;">
                        <li>
                            <a target="_blank" href="https://github.com/wadasworths">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a target="_blank" href="https://www.zhihu.com/people/solman">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa  fa-stack-1x fa-inverse">知</i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a target="_blank" href="https://weibo.com/u/5040234393">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-weibo fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a target="_blank" href="{% url 'rss' %}">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
        </div>
    </div>
    
    <!-- 文章分类目录 -->
    <h3 class="sidebar-title">文章归档</h3>
    <div class="card text-category">
        <div class="category">
            {% get_categories as category_list %}
            <div class="card-description">
                {% for category in category_list %}
                    <li class="side-category">
                        <a target="_blank" href="{% url 'blog:category' category.pk %}">
                            {{ category.name }} ({{ category.num_posts }})
                        </a>
                    </li>
                {% empty %}
                    <li class="side-category">
                        <a target="_blank" href="#">暂无分类</a>
                    </li>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- 文章标签 -->
    <h3 class="sidebar-title">所有标签</h3>
    <div class="card text-center">
        <div class="thumbnail">
                <div class="card-description">
                    {% get_tags as tag_list %}
                    <ul class="list-inline" style="margin-left: 0;">
                        {% for tag in tag_list %}
                            <li><a target="_blank" href="#">{{ tag.name }}</a></li>
                        {% empty %}
                            <li><a target="_blank" href="#">暂无标签</a></li>
                        {% endfor %}
                    </ul>
                </div>
        </div>
    </div>

    <!-- 最近推送文章 -->
    <h3 class="sidebar-title">最近推送</h3>
    <div class="card text-category">
        <div class="category">
            {% get_recent_posts as recent_list %}
            <div class="card-description">
                    {% for recent in recent_list %}
                        <li class="side-category">
                            <a target="_blank" href="{{ recent.get_absolute_url }}">{{ recent.title }}</a>
                        </li>
                    {% empty %}
                        <li class="side-category"><a target="_blank" href="/">暂无推送</a></li>
                    {% endfor %}
            </div>
        </div>
    </div>

</div>
{% endblock sidebar %}